/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuditLogSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'userId', 'action', 'entityType', 'entityId', 'oldValues', 'newValues', 'ipAddress', 'userAgent', 'createdAt'] as const
  $columns = AuditLogSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare userId: bigint | number | null
  @column()
  declare action: string
  @column()
  declare entityType: string
  @column()
  declare entityId: bigint | number | null
  @column()
  declare oldValues: string | null
  @column()
  declare newValues: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tokenableId: bigint | number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BookingSchema extends BaseModel {
  static $columns = ['id', 'bookingCode', 'organizationId', 'tripId', 'userId', 'ticketerId', 'agentId', 'source', 'type', 'passengerName', 'passengerPhone', 'passengerEmail', 'boardingStopId', 'alightingStopId', 'boardingStopOrder', 'alightingStopOrder', 'seatCount', 'totalAmount', 'currency', 'status', 'qrCodeData', 'checkedInAt', 'checkedOutAt', 'cancellationReason', 'cancelledById', 'offlineId', 'syncedAt', 'createdAt', 'updatedAt'] as const
  $columns = BookingSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare bookingCode: string
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare tripId: bigint | number
  @column()
  declare userId: bigint | number | null
  @column()
  declare ticketerId: bigint | number | null
  @column()
  declare agentId: bigint | number | null
  @column()
  declare source: string
  @column()
  declare type: string
  @column()
  declare passengerName: string
  @column()
  declare passengerPhone: string
  @column()
  declare passengerEmail: string | null
  @column()
  declare boardingStopId: bigint | number
  @column()
  declare alightingStopId: bigint | number
  @column()
  declare boardingStopOrder: number
  @column()
  declare alightingStopOrder: number
  @column()
  declare seatCount: number
  @column()
  declare totalAmount: string
  @column()
  declare currency: string
  @column()
  declare status: string
  @column()
  declare qrCodeData: string | null
  @column.dateTime()
  declare checkedInAt: DateTime | null
  @column.dateTime()
  declare checkedOutAt: DateTime | null
  @column()
  declare cancellationReason: string | null
  @column()
  declare cancelledById: bigint | number | null
  @column()
  declare offlineId: string | null
  @column.dateTime()
  declare syncedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class BookingSeatSchema extends BaseModel {
  static $columns = ['id', 'bookingId', 'tripSeatId', 'passengerName', 'createdAt'] as const
  $columns = BookingSeatSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare bookingId: bigint | number
  @column()
  declare tripSeatId: bigint | number
  @column()
  declare passengerName: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class CannedResponseSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'category', 'text', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = CannedResponseSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare category: string
  @column()
  declare text: string
  @column()
  declare sortOrder: number
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CitySchema extends BaseModel {
  static $columns = ['id', 'name', 'province', 'country', 'latitude', 'longitude', 'timezone', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare province: string
  @column()
  declare country: string
  @column()
  declare latitude: string | null
  @column()
  declare longitude: string | null
  @column()
  declare timezone: string
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ConversationSchema extends BaseModel {
  static $columns = ['id', 'bookingId', 'tripId', 'type', 'participantAId', 'participantBId', 'participantBOrgId', 'status', 'lastMessageAt', 'createdAt', 'updatedAt'] as const
  $columns = ConversationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare bookingId: bigint | number | null
  @column()
  declare tripId: bigint | number | null
  @column()
  declare type: string
  @column()
  declare participantAId: bigint | number
  @column()
  declare participantBId: bigint | number | null
  @column()
  declare participantBOrgId: bigint | number | null
  @column()
  declare status: string
  @column.dateTime()
  declare lastMessageAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FleetBookingSchema extends BaseModel {
  static $columns = ['id', 'bookingCode', 'organizationId', 'vehicleId', 'userId', 'driverUserId', 'type', 'title', 'description', 'startAt', 'endAt', 'pickupLocation', 'pickupLatitude', 'pickupLongitude', 'dropoffLocation', 'dropoffLatitude', 'dropoffLongitude', 'totalAmount', 'currency', 'status', 'notes', 'createdAt', 'updatedAt'] as const
  $columns = FleetBookingSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare bookingCode: string
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare vehicleId: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare driverUserId: bigint | number | null
  @column()
  declare type: string
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column.dateTime()
  declare startAt: DateTime
  @column.dateTime()
  declare endAt: DateTime
  @column()
  declare pickupLocation: string
  @column()
  declare pickupLatitude: string | null
  @column()
  declare pickupLongitude: string | null
  @column()
  declare dropoffLocation: string | null
  @column()
  declare dropoffLatitude: string | null
  @column()
  declare dropoffLongitude: string | null
  @column()
  declare totalAmount: string
  @column()
  declare currency: string
  @column()
  declare status: string
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class MessageSchema extends BaseModel {
  static $columns = ['id', 'conversationId', 'senderId', 'content', 'type', 'imageUrl', 'isRead', 'readAt', 'createdAt'] as const
  $columns = MessageSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare conversationId: bigint | number
  @column()
  declare senderId: bigint | number
  @column()
  declare content: string
  @column()
  declare type: string
  @column()
  declare imageUrl: string | null
  @column()
  declare isRead: boolean
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'organizationId', 'channel', 'type', 'title', 'body', 'data', 'status', 'errorMessage', 'externalId', 'sentAt', 'deliveredAt', 'readAt', 'createdAt', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare channel: string
  @column()
  declare type: string
  @column()
  declare title: string
  @column()
  declare body: string
  @column()
  declare data: string | null
  @column()
  declare status: string
  @column()
  declare errorMessage: string | null
  @column()
  declare externalId: string | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NotificationPreferenceSchema extends BaseModel {
  static $columns = ['id', 'userId', 'channel', 'type', 'enabled', 'createdAt', 'updatedAt'] as const
  $columns = NotificationPreferenceSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare channel: string
  @column()
  declare type: string
  @column()
  declare enabled: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'type', 'logoUrl', 'address', 'city', 'country', 'phone', 'email', 'taxId', 'requiredKycLevel', 'isPublic', 'isActive', 'settings', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare type: string
  @column()
  declare logoUrl: string | null
  @column()
  declare address: string | null
  @column()
  declare city: string
  @column()
  declare country: string
  @column()
  declare phone: string
  @column()
  declare email: string
  @column()
  declare taxId: string | null
  @column()
  declare requiredKycLevel: boolean
  @column()
  declare isPublic: boolean
  @column()
  declare isActive: boolean
  @column()
  declare settings: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OrganizationMemberSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'userId', 'role', 'isActive', 'joinedAt', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationMemberSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare role: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare joinedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentSchema extends BaseModel {
  static $columns = ['id', 'bookingId', 'fleetBookingId', 'organizationId', 'userId', 'amount', 'currency', 'method', 'provider', 'status', 'externalTransactionId', 'providerResponse', 'phoneNumber', 'paidAt', 'refundedAt', 'refundAmount', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = PaymentSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare bookingId: bigint | number | null
  @column()
  declare fleetBookingId: bigint | number | null
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare userId: bigint | number | null
  @column()
  declare amount: string
  @column()
  declare currency: string
  @column()
  declare method: string
  @column()
  declare provider: string | null
  @column()
  declare status: string
  @column()
  declare externalTransactionId: string | null
  @column()
  declare providerResponse: string | null
  @column()
  declare phoneNumber: string | null
  @column.dateTime()
  declare paidAt: DateTime | null
  @column.dateTime()
  declare refundedAt: DateTime | null
  @column()
  declare refundAmount: string | null
  @column()
  declare metadata: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentTransactionSchema extends BaseModel {
  static $columns = ['id', 'paymentId', 'type', 'amount', 'currency', 'status', 'providerReference', 'rawResponse', 'errorMessage', 'createdAt'] as const
  $columns = PaymentTransactionSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare paymentId: bigint | number
  @column()
  declare type: string
  @column()
  declare amount: string
  @column()
  declare currency: string
  @column()
  declare status: string
  @column()
  declare providerReference: string | null
  @column()
  declare rawResponse: string | null
  @column()
  declare errorMessage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class PayoutRecordSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'userId', 'amount', 'currency', 'method', 'provider', 'phoneNumber', 'status', 'externalReference', 'periodStart', 'periodEnd', 'notes', 'processedAt', 'createdAt', 'updatedAt'] as const
  $columns = PayoutRecordSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare userId: bigint | number
  @column()
  declare amount: string
  @column()
  declare currency: string
  @column()
  declare method: string
  @column()
  declare provider: string
  @column()
  declare phoneNumber: string | null
  @column()
  declare status: string
  @column()
  declare externalReference: string | null
  @column.date()
  declare periodStart: DateTime
  @column.date()
  declare periodEnd: DateTime
  @column()
  declare notes: string | null
  @column.dateTime()
  declare processedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PriceRuleSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'routeId', 'fromStopOrder', 'toStopOrder', 'seatClassId', 'vehicleId', 'basePrice', 'currency', 'priceMode', 'perSegmentPrice', 'perKmPrice', 'effectiveFrom', 'effectiveUntil', 'isPeak', 'peakMultiplier', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = PriceRuleSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare routeId: bigint | number
  @column()
  declare fromStopOrder: number | null
  @column()
  declare toStopOrder: number | null
  @column()
  declare seatClassId: bigint | number | null
  @column()
  declare vehicleId: bigint | number | null
  @column()
  declare basePrice: string
  @column()
  declare currency: string
  @column()
  declare priceMode: string
  @column()
  declare perSegmentPrice: string | null
  @column()
  declare perKmPrice: string | null
  @column.date()
  declare effectiveFrom: DateTime
  @column.date()
  declare effectiveUntil: DateTime | null
  @column()
  declare isPeak: boolean
  @column()
  declare peakMultiplier: string
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PushSubscriptionSchema extends BaseModel {
  static $columns = ['id', 'userId', 'endpoint', 'p256DhKey', 'authKey', 'userAgent', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = PushSubscriptionSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare endpoint: string
  @column()
  declare p256DhKey: string
  @column()
  declare authKey: string
  @column()
  declare userAgent: string | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RouteSchema extends BaseModel {
  static $columns = ['id', 'fromCityId', 'toCityId', 'distanceKm', 'estimatedDurationMin', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = RouteSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare fromCityId: bigint | number
  @column()
  declare toCityId: bigint | number
  @column()
  declare distanceKm: string | null
  @column()
  declare estimatedDurationMin: number | null
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RouteStopSchema extends BaseModel {
  static $columns = ['id', 'routeId', 'cityId', 'stopOrder', 'distanceFromStartKm', 'createdAt', 'updatedAt'] as const
  $columns = RouteStopSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare routeId: bigint | number
  @column()
  declare cityId: bigint | number
  @column()
  declare stopOrder: number
  @column()
  declare distanceFromStartKm: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeatClassSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'description', 'defaultMultiplier', 'color', 'icon', 'createdAt', 'updatedAt'] as const
  $columns = SeatClassSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare defaultMultiplier: string
  @column()
  declare color: string | null
  @column()
  declare icon: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeatLayoutSchema extends BaseModel {
  static $columns = ['id', 'vehicleId', 'name', 'rows', 'columns', 'layoutData', 'isDefault', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = SeatLayoutSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare vehicleId: bigint | number
  @column()
  declare name: string
  @column()
  declare rows: boolean
  @column()
  declare columns: boolean
  @column()
  declare layoutData: string
  @column()
  declare isDefault: boolean
  @column()
  declare isActive: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SeatReservationSchema extends BaseModel {
  static $columns = ['id', 'tripId', 'tripSeatId', 'userId', 'boardingStopOrder', 'alightingStopOrder', 'reservedUntil', 'createdAt'] as const
  $columns = SeatReservationSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tripId: bigint | number
  @column()
  declare tripSeatId: bigint | number
  @column()
  declare userId: bigint | number | null
  @column()
  declare boardingStopOrder: number
  @column()
  declare alightingStopOrder: number
  @column.dateTime()
  declare reservedUntil: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class TelegramLinkSchema extends BaseModel {
  static $columns = ['id', 'userId', 'telegramChatId', 'telegramUsername', 'isActive', 'linkedAt', 'createdAt', 'updatedAt'] as const
  $columns = TelegramLinkSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare userId: bigint | number
  @column()
  declare telegramChatId: bigint | number
  @column()
  declare telegramUsername: string | null
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare linkedAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TripSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'vehicleId', 'driverUserId', 'routeId', 'seatLayoutId', 'departureAt', 'estimatedArrivalAt', 'actualDepartureAt', 'actualArrivalAt', 'totalSeats', 'status', 'notes', 'isRecurring', 'recurrenceRule', 'allowIntermediateBoarding', 'createdAt', 'updatedAt'] as const
  $columns = TripSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare vehicleId: bigint | number
  @column()
  declare driverUserId: bigint | number
  @column()
  declare routeId: bigint | number
  @column()
  declare seatLayoutId: bigint | number
  @column.dateTime()
  declare departureAt: DateTime
  @column.dateTime()
  declare estimatedArrivalAt: DateTime | null
  @column.dateTime()
  declare actualDepartureAt: DateTime | null
  @column.dateTime()
  declare actualArrivalAt: DateTime | null
  @column()
  declare totalSeats: number
  @column()
  declare status: string
  @column()
  declare notes: string | null
  @column()
  declare isRecurring: boolean
  @column()
  declare recurrenceRule: string | null
  @column()
  declare allowIntermediateBoarding: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TripSeatSchema extends BaseModel {
  static $columns = ['id', 'tripId', 'seatIdentifier', 'seatClass', 'fullTripPrice', 'currency', 'isBlocked', 'features', 'createdAt', 'updatedAt'] as const
  $columns = TripSeatSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tripId: bigint | number
  @column()
  declare seatIdentifier: string
  @column()
  declare seatClass: string
  @column()
  declare fullTripPrice: string
  @column()
  declare currency: string
  @column()
  declare isBlocked: boolean
  @column()
  declare features: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class TripStopSchema extends BaseModel {
  static $columns = ['id', 'tripId', 'cityId', 'stopOrder', 'stopName', 'scheduledArrivalAt', 'scheduledDepartureAt', 'actualArrivalAt', 'actualDepartureAt', 'distanceFromStartKm', 'boardingEnabled', 'alightingEnabled', 'createdAt', 'updatedAt'] as const
  $columns = TripStopSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare tripId: bigint | number
  @column()
  declare cityId: bigint | number
  @column()
  declare stopOrder: number
  @column()
  declare stopName: string | null
  @column.dateTime()
  declare scheduledArrivalAt: DateTime | null
  @column.dateTime()
  declare scheduledDepartureAt: DateTime | null
  @column.dateTime()
  declare actualArrivalAt: DateTime | null
  @column.dateTime()
  declare actualDepartureAt: DateTime | null
  @column()
  declare distanceFromStartKm: string
  @column()
  declare boardingEnabled: boolean
  @column()
  declare alightingEnabled: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'email', 'phone', 'password', 'firstName', 'lastName', 'avatarUrl', 'locale', 'timezone', 'isSuperAdmin', 'isActive', 'emailVerifiedAt', 'phoneVerifiedAt', 'rememberMeToken', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare email: string | null
  @column()
  declare phone: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare firstName: string
  @column()
  declare lastName: string
  @column()
  declare avatarUrl: string | null
  @column()
  declare locale: string
  @column()
  declare timezone: string
  @column()
  declare isSuperAdmin: boolean
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column.dateTime()
  declare phoneVerifiedAt: DateTime | null
  @column()
  declare rememberMeToken: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VehicleSchema extends BaseModel {
  static $columns = ['id', 'organizationId', 'ownerUserId', 'type', 'brand', 'model', 'year', 'color', 'plateNumber', 'chassisNumber', 'totalSeats', 'visibility', 'isAvailableForRental', 'verificationStatus', 'isActive', 'rating', 'totalTrips', 'features', 'photos', 'insuranceExpiry', 'technicalVisitExpiry', 'createdAt', 'updatedAt'] as const
  $columns = VehicleSchema.$columns
  @column({ isPrimary: true })
  declare id: bigint | number
  @column()
  declare organizationId: bigint | number | null
  @column()
  declare ownerUserId: bigint | number
  @column()
  declare type: string
  @column()
  declare brand: string
  @column()
  declare model: string
  @column()
  declare year: number | null
  @column()
  declare color: string
  @column()
  declare plateNumber: string
  @column()
  declare chassisNumber: string | null
  @column()
  declare totalSeats: number
  @column()
  declare visibility: string
  @column()
  declare isAvailableForRental: boolean
  @column()
  declare verificationStatus: string
  @column()
  declare isActive: boolean
  @column()
  declare rating: string | null
  @column()
  declare totalTrips: number
  @column()
  declare features: string | null
  @column()
  declare photos: string | null
  @column.date()
  declare insuranceExpiry: DateTime | null
  @column.date()
  declare technicalVisitExpiry: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
